# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'surface.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(941, 714)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget_img = QtWidgets.QWidget(self.centralwidget)
        self.widget_img.setGeometry(QtCore.QRect(9, 29, 401, 311))
        self.widget_img.setObjectName("widget_img")
        self.label_img = QtWidgets.QLabel(self.centralwidget)
        self.label_img.setGeometry(QtCore.QRect(10, 10, 72, 15))
        self.label_img.setObjectName("label_img")
        self.textBrowser_choose  = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_choose.setGeometry(QtCore.QRect(420, 40, 361, 31))
        self.textBrowser_choose.setObjectName("textBrowser_choose")
        self.pushButton_choose = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_choose.setGeometry(QtCore.QRect(790, 40, 61, 31))
        self.pushButton_choose.setObjectName("pushButton_choose")
        self.textBrowser_reg = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_reg.setGeometry(QtCore.QRect(510, 120, 201, 41))
        self.textBrowser_reg.setObjectName("textBrowser_reg")
        self.label_reg = QtWidgets.QLabel(self.centralwidget)
        self.label_reg.setGeometry(QtCore.QRect(430, 120, 72, 41))
        self.label_reg.setObjectName("label_reg")
        self.label_rock = QtWidgets.QLabel(self.centralwidget)
        self.label_rock.setGeometry(QtCore.QRect(10, 340, 72, 31))
        self.label_rock.setObjectName("label_rock")
        self.widget_rock = QtWidgets.QWidget(self.centralwidget)
        self.widget_rock.setGeometry(QtCore.QRect(10, 370, 401, 301))
        self.widget_rock.setObjectName("widget_rock")
        self.label_oilimg = QtWidgets.QLabel(self.centralwidget)
        self.label_oilimg.setGeometry(QtCore.QRect(450, 340, 72, 31))
        self.label_oilimg.setObjectName("label_oilimg")
        self.widget_oilimg = QtWidgets.QWidget(self.centralwidget)
        self.widget_oilimg.setGeometry(QtCore.QRect(450, 370, 401, 291))
        self.widget_oilimg.setObjectName("widget_oilimg")
        self.label_oil = QtWidgets.QLabel(self.centralwidget)
        self.label_oil.setGeometry(QtCore.QRect(430, 230, 72, 15))
        self.label_oil.setObjectName("label_oil")
        self.lcdNumber_oil = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_oil.setGeometry(QtCore.QRect(510, 220, 191, 41))
        self.lcdNumber_oil.setObjectName("lcdNumber_oil")
        self.pushButton_submit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_submit.setGeometry(QtCore.QRect(860, 40, 61, 31))
        self.pushButton_submit.setObjectName("pushButton_submit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 941, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_choose.clicked.connect(self.msg)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_img.setText(_translate("MainWindow", "原始图片"))
        self.pushButton_choose.setText(_translate("MainWindow", "选择"))
        self.label_reg.setText(_translate("MainWindow", "分类结果"))
        self.label_rock.setText(_translate("MainWindow", "岩堆检测"))
        self.label_oilimg.setText(_translate("MainWindow", "油气图"))
        self.label_oil.setText(_translate("MainWindow", "油气含量"))
        self.pushButton_submit.setText(_translate("MainWindow", "确定"))

    def msg(self):
        print('+' * 10)
        self.textBrowser_choose.setText("www")
        # fileName, _ = QFileDialog.getOpenFileName(self, "选取文件", "C:/",  "All Files (*);;img Files (*.png *.jpg *.bmp)")
        # print(fileName)
        # self.textBrowser_choose.setText(fileName)
